services:
  server:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    # working_dir: /var/www/html/${PROJECT_NAME} # Example: example-app
    # command: ${RUN_COMMAND} # Example: php artisan serve --host=0.0.0.0 --port=80
  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
volumes:
  db_data:
  smtp4dev-data:
